
var _ = require('dry-underscore');

function TestRunner(options){
    this.Reporters = [];
    this.Options = options;
}

TestRunner.prototype.RunSuiteFile = function(suiteFilePath, callback){

};

TestRunner.prototype.RunSuite = function(suite, state, callback){

    this.Report("SuiteStart", state);

    _.each(suite, function(test){
        this.Report("TestStart", state);

    });
};

TestRunner.prototype.Report = function(event){
    var args = _.toArray(arguments);
    args.shift();

    _.each(this.Reporters, function(reporter){
        if(reporter[event]){ reporter[event].apply(null, args); }
    });
};
